config/routes.rb
Lottery::Application.routes.draw do
  resources :customs

  root :to => 'investors#new'
  
  resources :prizecounts

  resources :preregs

  resources :prizes

  resources :days

  resources :investors do
    member do
      get 'roll_again'
    end
    
    
  end

end

app/models/custom.rb
class Custom < ActiveRecord::Base
end

app/controllers/customs_controller.rb
class CustomsController < ApplicationController
  # GET /customs
  # GET /customs.xml
  def index
    @customs = Custom.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customs }
    end
  end

  # GET /customs/1
  # GET /customs/1.xml
  def show
    @custom = Custom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @custom }
    end
  end

  # GET /customs/new
  # GET /customs/new.xml
  def new
    @custom = Custom.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @custom }
    end
  end

  # GET /customs/1/edit
  def edit
    @custom = Custom.find(params[:id])
  end

  # POST /customs
  # POST /customs.xml
  def create
    @custom = Custom.new(params[:custom])

    respond_to do |format|
      if @custom.save
        format.html { redirect_to(@custom, :notice => 'Custom was successfully created.') }
        format.xml  { render :xml => @custom, :status => :created, :location => @custom }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @custom.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customs/1
  # PUT /customs/1.xml
  def update
    @custom = Custom.find(params[:id])

    respond_to do |format|
      if @custom.update_attributes(params[:custom])
        format.html { redirect_to(@custom, :notice => 'Custom was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @custom.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customs/1
  # DELETE /customs/1.xml
  def destroy
    @custom = Custom.find(params[:id])
    @custom.destroy

    respond_to do |format|
      format.html { redirect_to(customs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/views/customs/_form.html.erb
<%= form_for(@custom) do |f| %>
  <% if @custom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom.errors.count, "error") %> prohibited this custom from being saved:</h2>

      <ul>
      <% @custom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apple %><br />
    <%= f.text_field :apple %>
  </div>
  <div class="field">
    <%= f.label :bundle %><br />
    <%= f.text_field :bundle %>
  </div>
  <div class="field">
    <%= f.label :pickone %><br />
    <%= f.text_field :pickone %>
  </div>
  <div class="field">
    <%= f.label :nothing %><br />
    <%= f.text_field :nothing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customs/edit.html.erb
<h1>Editing custom</h1>

<%= render 'form' %>

<%= link_to 'Show', @custom %> |
<%= link_to 'Back', customs_path %>

app/views/customs/index.html.erb
<h1>Listing customs</h1>

<table>
  <tr>
    <th>Apple</th>
    <th>Bundle</th>
    <th>Pickone</th>
    <th>Nothing</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customs.each do |custom| %>
  <tr>
    <td><%= custom.apple %></td>
    <td><%= custom.bundle %></td>
    <td><%= custom.pickone %></td>
    <td><%= custom.nothing %></td>
    <td><%= link_to 'Show', custom %></td>
    <td><%= link_to 'Edit', edit_custom_path(custom) %></td>
    <td><%= link_to 'Destroy', custom, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Custom', new_custom_path %>

app/views/customs/new.html.erb
<h1>New custom</h1>

<%= render 'form' %>

<%= link_to 'Back', customs_path %>

app/views/customs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Apple:</b>
  <%= @custom.apple %>
</p>

<p>
  <b>Bundle:</b>
  <%= @custom.bundle %>
</p>

<p>
  <b>Pickone:</b>
  <%= @custom.pickone %>
</p>

<p>
  <b>Nothing:</b>
  <%= @custom.nothing %>
</p>


<%= link_to 'Edit', edit_custom_path(@custom) %> |
<%= link_to 'Back', customs_path %>