config/routes.rb
Lottery::Application.routes.draw do
  resources :customs

  root :to => 'investors#new'
  
  resources :prizecounts

  resources :preregs

  resources :prizes

  resources :days

  resources :investors do
    member do
      get 'roll_again'
    end
    
    
  end

end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  # GET /days
  # GET /days.xml
  def index
    @days = Day.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @days }
    end
  end

  # GET /days/1
  # GET /days/1.xml
  def show
    @day = Day.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @day }
    end
  end

  # GET /days/new
  # GET /days/new.xml
  def new
    @day = Day.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @day }
    end
  end

  # GET /days/1/edit
  def edit
    @day = Day.find(params[:id])
  end

  # POST /days
  # POST /days.xml
  def create
    @day = Day.new(params[:day])

    respond_to do |format|
      if @day.save
        format.html { redirect_to(@day, :notice => 'Day was successfully created.') }
        format.xml  { render :xml => @day, :status => :created, :location => @day }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @day.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /days/1
  # PUT /days/1.xml
  def update
    @day = Day.find(params[:id])

    respond_to do |format|
      if @day.update_attributes(params[:day])
        format.html { redirect_to(@day, :notice => 'Day was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @day.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.xml
  def destroy
    @day = Day.find(params[:id])
    @day.destroy

    respond_to do |format|
      format.html { redirect_to(days_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
	<select id="day_number" name="day[number]">
	  <option value="1">(1) Base</option>
	  <option value="2">(2) No Apple for you</option>
	  <option value="3">(3) Apple Accelerator 1 (5%)</option>
	  <option value="4">(4) Apple Accelerator 2 (25%)</option>
	  <option value="5">(5) Apple Accelerator 3 (50%)</option>
	  <option value="6">(6) EMERGENCY - CUSTOM %</option>
	</select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <tr>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @days.each do |day| %>
  <tr>
    <td><%= day.number %></td>
    <td><%= link_to 'Show', day %></td>
    <td><%= link_to 'Edit', edit_day_path(day) %></td>
    <td><%= link_to 'Destroy', day, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @day.number %>
</p>