config/routes.rb
Lottery::Application.routes.draw do
  resources :customs

  root :to => 'investors#new'
  
  resources :prizecounts

  resources :preregs

  resources :prizes

  resources :days

  resources :investors do
    member do
      get 'roll_again'
    end
    
    
  end

end

app/models/investor.rb
class Investor < ActiveRecord::Base
  belongs_to :prize
  belongs_to :prize2, :class_name => 'Prize'
  
  validates_uniqueness_of :email
  
  def set_prize(investor, email)
    
    @yournum = rand(100)
    @day = Day.find_by_id(1)
    @custom = Custom.find_by_id(1)
    @apple = Prizecount.find_by_id(1)
    #if email != nil
     # investor.last_name = email.name
    #end 
    
    if @day.number == 1
  
  
      if @yournum == 1
      investor.prize_id = 2
      elsif @yournum > 1 && @yournum <=4
      investor.prize_id = 1
      elsif @yournum > 4 && @yournum <=15
      investor.prize_id = 3
      elsif @yournum > 15 && @yournum <=100
      investor.prize_id = 4
      end
  
    elsif @day.number == 2
      
      if @yournum < 0
      investor.prize_id = 2
      elsif @yournum > 0 && @yournum <=3
      investor.prize_id = 1
      elsif @yournum > 3 && @yournum <=15
      investor.prize_id = 3
      elsif @yournum > 15 && @yournum <=100
      investor.prize_id = 4
      end
      
    elsif @day.number == 3      
      
      if @yournum <= 5
      investor.prize_id = 2
      elsif @yournum > 5 && @yournum <=8
      investor.prize_id = 1
      elsif @yournum > 8 && @yournum <= 20
      investor.prize_id = 3
      elsif @yournum > 20 && @yournum <=100
      investor.prize_id = 4
      end
          
    elsif @day.number == 4      
      
      if @yournum <= 25
      investor.prize_id = 2
      elsif @yournum > 25 && @yournum <=28
      investor.prize_id = 1
      elsif @yournum > 28 && @yournum <= 40
      investor.prize_id = 3
      elsif @yournum > 40 && @yournum <=100
      investor.prize_id = 4
      end
          
    elsif @day.number == 5      
      
      if @yournum <= 50
      investor.prize_id = 2
      elsif @yournum > 50 && @yournum <=53
      investor.prize_id = 1
      elsif @yournum > 53 && @yournum <= 65
      investor.prize_id = 3
      elsif @yournum > 65 && @yournum <=100
      investor.prize_id = 4
      end
      
    elsif @day.number == 6  
      
      if @yournum <= @custom.apple
      investor.prize_id = 2
      elsif @yournum > @custom.apple && @yournum <= @custom.bundle
      investor.prize_id = 1
      elsif @yournum > @custom.bundle && @yournum <= @custom.pickone
      investor.prize_id = 3
      elsif @yournum > @custom.pickone && @yournum <=100
      investor.prize_id = 4
      end
    
    end
    
    if investor.prize_id == 2
      @apple.prize_count = @apple.prize_count+1
      @apple.save!
      @day.number = 2
      @day.save!
    end
    
  end
  
  def set_second_prize(investor)
    
     @yournum = rand(100)
      @day = Day.find_by_id(1)
      @custom = Custom.find_by_id(1)
      @apple = Prizecount.find_by_id(1)

      if @day.number == 1


        if @yournum == 1
        investor.prize2_id = 2
        elsif @yournum > 1 && @yournum <=4
        investor.prize2_id = 1
        elsif @yournum > 4 && @yournum <=15
        investor.prize2_id = 3
        elsif @yournum > 15 && @yournum <=100
        investor.prize2_id = 4
        end

      elsif @day.number == 2

        if @yournum < 0
        investor.prize2_id = 2
        elsif @yournum > 0 && @yournum <=3
        investor.prize2_id = 1
        elsif @yournum > 3 && @yournum <=15
        investor.prize2_id = 3
        elsif @yournum > 15 && @yournum <=100
        investor.prize2_id = 4
        end

      elsif @day.number == 3      

        if @yournum <= 5
        investor.prize2_id = 2
        elsif @yournum > 5 && @yournum <=8
        investor.prize2_id = 1
        elsif @yournum > 8 && @yournum <= 20
        investor.prize2_id = 3
        elsif @yournum > 20 && @yournum <=100
        investor.prize2_id = 4
        end

      elsif @day.number == 4      

        if @yournum <= 25
        investor.prize2_id = 2
        elsif @yournum > 25 && @yournum <=28
        investor.prize2_id = 1
        elsif @yournum > 28 && @yournum <= 40
        investor.prize2_id = 3
        elsif @yournum > 40 && @yournum <=100
        investor.prize2_id = 4
        end

      elsif @day.number == 5      

        if @yournum <= 50
        investor.prize2_id = 2
        elsif @yournum > 50 && @yournum <=53
        investor.prize2_id = 1
        elsif @yournum > 53 && @yournum <= 65
        investor.prize2_id = 3
        elsif @yournum > 65 && @yournum <=100
        investor.prize2_id = 4
        end

      elsif @day.number == 6  

        if @yournum <= @custom.apple
        investor.prize2_id = 2
        elsif @yournum > @custom.apple && @yournum <= (@custom.bundle+@custom.apple)
        investor.prize2_id = 1
        elsif @yournum > (@custom.bundle+@custom.apple) && @yournum <= (@custom.pickone+@custom.bundle+@custom.apple)
        investor.prize2_id = 3
        elsif @yournum > (@custom.pickone+@custom.bundle+@custom.apple) && @yournum <=100
        investor.prize2_id = 4
        end

      end

      if investor.prize2_id == 2
        @apple.prize_count = @apple.prize_count+1
        @apple.save!
        @day.number = 2
        @day.save!
      end
    
    investor.entries = 2
    
  end
  
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  # GET /investors
  # GET /investors.xml
  def index
    @investors = Investor.all
    @day = Day.find_by_id(1)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @investors }
    end
  end

  # GET /investors/1
  # GET /investors/1.xml
  def show
    @investor = Investor.find(params[:id])
    @prereg = Prereg.find_by_email(@investor.email)
    @day = Day.find_by_id(1)
    @apple = Prizecount.find_by_id(1)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @investor }
    end
  end

  # GET /investors/new
  # GET /investors/new.xml
  def new
    @investor = Investor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @investor }
    end
  end

  # GET /investors/1/edit
  def edit
    @investor = Investor.find(params[:id])
  end

  def roll_again
    
    @investor = Investor.find(params[:id])
    @investor.set_second_prize(@investor)
    
    if @investor.save
      redirect_to @investor
    else
      flash[:error] = "..."
      render :action => 'new'
    end
    
  end

  # POST /investors
  # POST /investors.xml
  def create
    @investor = Investor.new(params[:investor])
    @investor.email = @investor.email.downcase
    @prereg = Prereg.find_by_email(@investor.email)
    
    @investor.set_prize(@investor, @prereg)
    
    if @investor.save
      redirect_to @investor
    else
      flash[:error] = "..."
      render :action => 'new'
    end
  end

  # PUT /investors/1
  # PUT /investors/1.xml
  def update
    @investor = Investor.find(params[:id])

    respond_to do |format|
      if @investor.update_attributes(params[:investor])
        format.html { redirect_to(@investor, :notice => 'Investor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @investor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /investors/1
  # DELETE /investors/1.xml
  def destroy
    @investor = Investor.find(params[:id])
    @investor.destroy

    respond_to do |format|
      format.html { redirect_to(investors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/investors_helper.rb
module InvestorsHelper
end

app/views/investors/_form.html.erb
<%= form_for(@investor) do |f| %>
  <% if @investor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investor.errors.count, "error") %> prohibited this investor from being saved:</h2>

      <ul>
      <% @investor.errors.full_messages.each do |msg| %>
        <li style="list-style:none;"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :first_name, :class => "forms", :value => "First Name", :onFocus => "if(this.value==this.defaultValue) this.value='';", 
	:onBlur => "if(this.value=='') this.value=this.defaultValue;" %>
  </div>
  <div class="field">
    <%= f.text_field :last_name, :class => "forms", :value => "Last Name", :onFocus => "if(this.value==this.defaultValue) this.value='';", 
	:onBlur => "if(this.value=='') this.value=this.defaultValue;" %>
  </div>
  <div class="field">
    <%= f.text_field :email, :class => "forms", :value => "Email", :onFocus => "if(this.value==this.defaultValue) this.value='';", 
	:onBlur => "if(this.value=='') this.value=this.defaultValue;" %>
  </div>
  <div class="field">
    <%= f.text_field :phone, :class => "forms", :value => "Phone", :onFocus => "if(this.value==this.defaultValue) this.value='';", 
	:onBlur => "if(this.value=='') this.value=this.defaultValue;" %>
	
	<%= f.hidden_field :entries, :value => 1 %>
  </div>
  <div class="actions">
    <%= f.submit :class => "roll-button", :value => ""%>
  </div>
<% end %>

app/views/investors/edit.html.erb
<h1>Editing investor</h1>

<%= render 'form' %>

<%= link_to 'Show', @investor %> |
<%= link_to 'Back', investors_path %>

app/views/investors/index.html.erb
<h1>Listing investors</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Prize</th>
    <th>Prize2</th>
    <th>Entries</th>
    <th>Created At</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @investors.each do |investor| %>
  <tr>
    <td><%= investor.first_name %></td>
    <td><%= investor.last_name %></td>
    <td><%= investor.email %></td>
    <td><%= investor.phone %></td>
    <td><%= investor.prize.name %></td>
    <td><% if investor.prize2 != nil %>
	<%= investor.prize2.name %>
	<% end %></td>
    <td><%= investor.entries %></td>
    <td><%= investor.created_at.strftime('%m/%d/%y %I:%M') %></td>
    <td><%= link_to 'Show', investor %></td>
    <td><%= link_to 'Edit', edit_investor_path(investor) %></td>
    <td><%= link_to 'Destroy', investor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />

<a href="/preregs">Add a preregistrant</a><Br/>
<%= link_to 'New Investor', new_investor_path %>
<a href="/days/1/edit">Set the odds</a>
<br/>The odd number is currently: <%= @day.number %>
<a href="/customs/1/edit">Set the CUSTOM EMERGENCY NUMBERS - ODDS MUST BE SET TO 6</a>

app/views/investors/new.html.erb
<div class="header"><a href="/"><div class="logo"></div></a></div>
<div class="middle">
		
		<div class="flag">
			<img src="/images/right-side-text.png" style="float:right;margin:-60px -290px 0 0;">
		<%= render 'form' %></div>
</div>
<div class="dudes"><img src="/images/bottom-dudes.png"></div>

app/views/investors/show.html.erb
<div class="header"><a href="/"><div class="logo"></div></a></div>
<div class="middle">
	<div class="flag" style="color:#fff;font-size:18px;line-height:27px;">
		<img src="/images/right-side-text.png" style="float:right;margin:-60px -290px 0 0;">
		
		  <div class="field">
		    Thanks for entering our contest.
		  </div>
		  <div class="field">
				<% if @investor.prize_id == 2 %>
					<% if @apple.prize_count == 1 %>
					 Congratulations <%= @investor.first_name %>! You’ve just won an Apple TV. Yippee!
					<% elsif  @apple.prize_count == 2 %>
					 Congratulations <%= @investor.first_name %>! You’ve just won an Apple iPod. Way to go!
					<% elsif  @apple.prize_count == 3 %>
					 Congratulations <%= @investor.first_name %>! You’ve just won an Apple iPad. Wahoo!
					<% end %>
				<% elsif @investor.prize_id == 1 %>
				 Congratulations <%= @investor.first_name %>! You’ve just won a Currensee hat and t-shirt. Let us be the first to say, you are looking good!
				<% elsif @investor.prize_id == 3 %>
				 Congratulations <%= @investor.first_name %>! You’ve just won some cool Currensee gear. It’s a tough decision t-shirt or hat, what will you choose?
				<% elsif @investor.prize_id == 4 %>
				We’re very sorry but you didn’t win anything. Don’t cry though, think of how fun this was! 
				<% end %>
		  </div>
			<% if @prereg != nil %>
		  <div class="field">
				<% if @investor.prize2_id == 2 %>
					<% if @apple.prize_count == 1 %>
					 Congratulations <%= @investor.first_name %>! You’ve just won an Apple TV. Yippee!
					<% elsif  @apple.prize_count == 2 %>
					 Congratulations <%= @investor.first_name %>! You’ve just won an Apple iPod. Way to go!
					<% elsif  @apple.prize_count == 3 %>
					 Congratulations <%= @investor.first_name %>! You’ve just won an Apple iPad. Wahoo!
					<% end %>
				<% elsif @investor.prize2_id == 1 %>
				 Congratulations <%= @investor.first_name %>! You’ve just won a Currensee hat and t-shirt. Let us be the first to say, you are looking good!
				<% elsif @investor.prize2_id == 3 %>
				 Congratulations <%= @investor.first_name %>! You’ve just won some cool Currensee gear. It’s a tough decision t-shirt or hat, what will you choose?
				<% elsif @investor.prize2_id == 4 && @investor.prize_id == 4 %>
				Our sincerest apologies but you still didn’t win, better luck at the next show! 
				<% elsif @investor.prize2_id == 4 && @investor.prize_id != 4 %>
				We’re very sorry but you didn’t win anything. Don’t cry though, think of how fun this was! 
				<% end %>
		  </div>
			<% end %>
		  <!--div class="field">
		   You've entered <%= @investor.entries %> times
		  </div-->
		<% if @prereg != nil && @investor.entries <= 1 %>
		Lucky you, since you pre-registered you get another chance to win a prize!</strong>
		  <div class="actions">
		    <a href="<%= roll_again_investor_path(@investor)%>"><div class="roll-button"></div></a>
		  </div>
		<% end %>
		
	</div>
</div>
<div class="dudes"><img src="/images/bottom-dudes.png"></div>



<!--><p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @investor.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @investor.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @investor.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @investor.phone %>
</p>

<p>
  <b>Prize (<%= @investor.prize_id %>):</b>
	<% if @investor.prize_id == 2 %>
	YOU WON AN APPLE PRODUCT
	<% elsif @investor.prize_id == 1 %>
	You won a shirt and a hat
	<% elsif @investor.prize_id == 3 %>
	You won a shirt or a hat
	<% elsif @investor.prize_id == 4 %>
	You didnt win shit.
	<% end %>
  
</p>

<p>
  <b>Prize2:</b>
  <%= @investor.prize2_id %>
</p>

<p>
  <b>Entries:</b>
  <%= @investor.entries %>
</p>

Today is day number: <%= @day.number %><br/>


<%= link_to 'Edit', edit_investor_path(@investor) %> |
<%= link_to 'Back', investors_path %>
-->