config/routes.rb
Lottery::Application.routes.draw do
  resources :customs

  root :to => 'investors#new'
  
  resources :prizecounts

  resources :preregs

  resources :prizes

  resources :days

  resources :investors do
    member do
      get 'roll_again'
    end
    
    
  end

end

app/models/prereg.rb
class Prereg < ActiveRecord::Base
end

app/controllers/preregs_controller.rb
class PreregsController < ApplicationController
  # GET /preregs
  # GET /preregs.xml
  def index
    @preregs = Prereg.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @preregs }
    end
  end

  # GET /preregs/1
  # GET /preregs/1.xml
  def show
    @prereg = Prereg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prereg }
    end
  end

  # GET /preregs/new
  # GET /preregs/new.xml
  def new
    @prereg = Prereg.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prereg }
    end
  end

  # GET /preregs/1/edit
  def edit
    @prereg = Prereg.find(params[:id])
  end

  # POST /preregs
  # POST /preregs.xml
  def create
    @prereg = Prereg.new(params[:prereg])
    @prereg.email = @prereg.email.downcase
    
    respond_to do |format|
      if @prereg.save
        format.html { redirect_to(@prereg, :notice => 'Prereg was successfully created.') }
        format.xml  { render :xml => @prereg, :status => :created, :location => @prereg }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prereg.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /preregs/1
  # PUT /preregs/1.xml
  def update
    @prereg = Prereg.find(params[:id])

    respond_to do |format|
      if @prereg.update_attributes(params[:prereg])
        format.html { redirect_to(@prereg, :notice => 'Prereg was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prereg.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /preregs/1
  # DELETE /preregs/1.xml
  def destroy
    @prereg = Prereg.find(params[:id])
    @prereg.destroy

    respond_to do |format|
      format.html { redirect_to(preregs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/preregs_helper.rb
module PreregsHelper
end

app/views/preregs/_form.html.erb
<%= form_for(@prereg) do |f| %>
  <% if @prereg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prereg.errors.count, "error") %> prohibited this prereg from being saved:</h2>

      <ul>
      <% @prereg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preregs/edit.html.erb
<h1>Editing prereg</h1>

<%= render 'form' %>

<%= link_to 'Show', @prereg %> |
<%= link_to 'Back', preregs_path %>

app/views/preregs/index.html.erb
<h1>Listing preregs</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @preregs.each do |prereg| %>
  <tr>
    <td><%= prereg.email %></td>
    <td><%= prereg.name %></td>
    <td><%= link_to 'Show', prereg %></td>
    <td><%= link_to 'Edit', edit_prereg_path(prereg) %></td>
    <td><%= link_to 'Destroy', prereg, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prereg', new_prereg_path %>

app/views/preregs/new.html.erb
<h1>New prereg</h1>

<%= render 'form' %>

<%= link_to 'Back', preregs_path %>

app/views/preregs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @prereg.email %>
</p>

<p>
  <b>Name:</b>
  <%= @prereg.name %>
</p>


<%= link_to 'Edit', edit_prereg_path(@prereg) %> |
<%= link_to 'Back', preregs_path %>